### ISSUE TITLE
Estimating Plot Size takes too much time

### ISSUE THREAD

**Issue by ozgunozerk** [subspace/subspace-desktop#128]
We have to somehow enhance this. It is bottlenecking the development process as well

**Comment by ozgunozerk** [comment]
If we are syncing from bootstrap, change it to sync from peers

**Comment by ImmaZoni** [comment]
The root cause of this should be our main focus. (imo)

This seems to be correlated to the domain/bootstrap node.

For example. 
Earlier I could not load the Explorer on my browser (30min+)
At this same time I was unable to run subspace-desktop through setup because it was hanging on querying the estimated size.

Shouldn't this be queried with the local node instead of relying on the explorer?

**Comment by 1devNdogs** [comment]
Now it will take no time.

**Comment by ozgunozerk** [comment]
Still takes too much time. Tried on MacOS, builded with `yarn build`, it was `main` branch
