### ISSUE TITLE
Can't continue with existing directory/plot

### ISSUE THREAD

**Issue by nazar-pc** [subspace/subspace-desktop#154]
I had 0.2.2 before and it worked fine. I upgraded to 0.3.2 and it started crashing, now with 0.3.3 it starts, but asks me to go through setup process even though I did it before. Fine, I can go through setup again, but now when I select old directory it doesn't want to accept it:

![Знімок екрана з 2022-04-09 20-46-59](https://user-images.githubusercontent.com/928965/162585619-4782f33d-43f0-48e1-ba0b-e0b2b130d77d.png)

Maybe this is expected, but I find it unexpected and annoying.

**Comment by nazar-pc** [comment]
I was able to trick it into using it by renaming original into something different, going through setup process, closing the app and renaming back to what it was and starting an app again (so it thinks it is the files it created, but it is MY files now :smiling_imp: )

**Comment by ozgunozerk** [comment]
Yes. This scenario is not covered:
User upgrades the application to the newer version, but has plots from previous version. We were handling this with the `config` file. But since we removed it, the config disappears and app thinks it is starting from scratch. Hence, rejects the previous files.

We need to fix this

**Comment by nazar-pc** [comment]
Config disappears from where?

**Comment by ozgunozerk** [comment]
Config is now a part of the application. So when the user upgrades the app to the newer version, the config for the older version is not transferred to the newer version. Hence, when the user launches the newer version, the app thinks it is the first time launch (because there is no config for the newer version). And requires the folder to be used to be empty.

This should not be the case though, if the folder to be used is not empty, it should scan the files and generate a new config file for itself.

This not implemented yet.

**Comment by nazar-pc** [comment]
Hm... the fact that configuration is not transferred on upgrades sounds like the root issue here to me. It really should be.

**Comment by ozgunozerk** [comment]
Yes... We were handling this with an external config file. We can revert to this previous strategy, or I can research some other ways of doing this if there any?

**Comment by nazar-pc** [comment]
Generally I see you're using local storage. I'm not 100% sure it is ideal, worth researching options I guess.
