### ISSUE TITLE
Change the wording for `Quick Start` and `Advanced`

### ISSUE THREAD

**Issue by ozgunozerk** [subspace/subspace-desktop#171]
Change the wording in order to better the the user experience (more descriptive/helpful words)

**Comment by ozgunozerk** [comment]
@isSerge @DianaPertseva @rg3l3dr @nazar-pc @ImmaZoni 

We can start this async discussion here. **Can we find descriptive/helpful words for these paths?** is the question.

What we already thought is: `I'm farming for the first time` for `Quick Start`, and `I'm a farmer already` (or something like that) for the `Advanced`. 

I disagreed with this suggestion. A user may want to import their reward address from polkadot address (`advanced` path) but may still be farming for the first time. 

My suggestion is to keep the `Quick Start` as is, and change the `Advanced` to `Import a Reward Address`

Any feedback is welcome

**Comment by ImmaZoni** [comment]
I think we should phrased based on the intent of the menu, At a very core level on this screen we are really asking the user if they 
a. do not have a wallet, and want us to generate one for them
b. do have a wallet, and want to import it into the farmer for them

due to that i think we should explain this, and frame it as `create me a wallet` & `import a reward address`

**Comment by nazar-pc** [comment]
"Import a Reward Address" -> "I have a wallet already" (it isn't really importing anything, just specifying)

**Comment by ozgunozerk** [comment]
`create me a wallet` & `I have a wallet already`
sounds good to me, will wait for a bit longer for finalizing this decision
