### ISSUE TITLE
Stuck on `Fetching network data...` though node is actually syncing.

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/subspace-desktop#193]
When attempting to start v0.4.4 on windows i am facing an error where the GUI shows `Fetching Network Data...` and never shows how much its synced etc, but if you look on telemetry it is actually syncing blocks. 

See screenshot attached
![image](https://user-images.githubusercontent.com/31865152/166855166-cfbe8d1e-e037-476e-b9be-9348cbb857cd.png)

**Comment by ozgunozerk** [comment]
You are right. 
The issue is, the `rewardAddress` logic was unnecessarily complicated before `multi-replica` changes. And that complicated structure was causing many edge cases. This is one of them. I could fix this specific bug as well, but feeling like another edge case will arise.

Multi-replica branch has none of these problems, because of the improved and simplified `rewardAddress` logic.

I reflected those changes in here as well, and tested locally. Should work fine now 👍

**Comment by ImmaZoni** [comment]
![image](https://user-images.githubusercontent.com/31865152/166947130-7d475e29-d967-4d62-b37d-d01662b6df58.png)

Issue is persistent on v0.4.5
