### ISSUE TITLE
Persist node name across restarts

### ISSUE THREAD

**Issue by nazar-pc** [subspace/subspace-desktop#197]
Right now we just generate a random name on each restart, we need to at least make it persistent, maybe even customizable in the future.

**Comment by isSerge** [comment]
Edit node name feature implemented #219

**Comment by ozgunozerk** [comment]
Will need some changes in the backend for editable node name, reopening

**Comment by ozgunozerk** [comment]
This is actually working, but I will consider it as DONE, since it is working with a workaround of relaunching the whole app, instead of just restarting the node and farmer in the backend. 
There is a bug about restarting the node, will open an issue about that on the monorepo after discussing it with Nazar

**Comment by ozgunozerk** [comment]
The aforementioned bug is fixed: https://github.com/subspace/subspace/issues/578
