### ISSUE TITLE
State does not persist when rebooting while still in plotting/syncing phase. 

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/subspace-desktop#203]
# System
Windows 11
v0.4.8

# Issue
When in the syncing/plotting phase if the user reboots their computer or the application it is reset to fresh setup and requires the user to start over. Considering how windows is already a longer sync than others this issue is very frustrating (from first hand experience 😆)

**Comment by ozgunozerk** [comment]
This issue is also present in `main` branch. 
It is due to -> when imported mnemonic, or when there is a leftover reward address from previous runs, the app is not setting/updating `plot` related configurations. Fix is on the way. 
Thanks Justin 👍 

Please include the `log` file next time in here too!
