### ISSUE TITLE
Update Dependencies #6

### ISSUE THREAD

**Issue by achiurizo** [subspace/subspace-desktop#344]
:clipboard: [slack audit](https://subspacenetwork.slack.com/files/U03QDGL1Q77/F044AJMDUBT/subspace_network_desktop_farmer_-_final_report.pdf) `#6`

We should update the dependencies listed from the Audit see

**Comment by isSerge** [comment]
- [ ] update frontend dependencies
- [ ] update rust dependencies

**Comment by ozgunozerk** [comment]
for `time` dependency, we don't need to fix it. In summary, `time` package is only used by `chrono` in our dependency tree. And `chrono` does not use the vulnerable part of the `time` crate. https://github.com/chronotope/chrono/issues/602#issuecomment-1224908456

**Comment by isSerge** [comment]
As mentioned on the Dev Sync, frontend dependencies with vulnerabilities (`got` and `git-clone`) are `devDependencies`, which are not included in the production bundle. I also notified Quasar devs about these vulnerabilities and they promised to fix/update those

**Comment by ozgunozerk** [comment]
The remaining unticked dependencies above, are not security issues, but rather warnings about unmaintained dependencies. Thus, they are not blockers for the audit. It is sufficient to have an issue for them to keep track. 

These are indirect dependencies, and there are **opened issues** for replacing these unmaintained ones with alternatives. When the parent dependencies of these indirect ones, replace these unmaintained ones, we can upgrade our dependencies as well, and these minor warnings will be resolved then.

Again, since these are NOT security issues, it's not mandatory but a good to have to replace them when the appropriate time comes.
