### ISSUE TITLE
MacOS dock icon is a little bit too big

### ISSUE THREAD

**Issue by ozgunozerk** [subspace/subspace-desktop#52]
Although it is a bit too big, it doesn't look ugly, resolution is quite nice, and it looks outstanding compared to other apps. This is for sure not a priority, but we can fix it sometime later.

<img width="515" alt="image" src="https://user-images.githubusercontent.com/32795992/154661296-6da8ec16-fedb-44ff-9172-d9cab95e48ae.png">

**Comment by 1devNdogs** [comment]
This can be fixed by regenerating icons with the `tauri icon subspace-logo.png` command, I recently updated this to fix Linux bundles, exporting the latest logo from Figma with correct sizes, but missing padding. 

On Linux at least the `dock` icon and `tray` icon was looking good, let me check docs to create a new `subspace-logo.png` to fit all OS icons.
